# Page d'accueil
emal_homepage:
    path:       /
    defaults: { _controller: emalBundle:Default:index }
    
# Route d'erreur
erreur:
    path:       /error/{code}
    defaults:   { _controller: emalBundle:Default:erreur }